DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS player CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS doubleGame CASCADE;
DROP TABLE IF EXISTS singleGame CASCADE;
DROP TABLE IF EXISTS trainingGame CASCADE;
DROP TABLE IF EXISTS court CASCADE;
DROP TABLE IF EXISTS sequences CASCADE;
